---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-mysql-disk
spec: 
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 2Gi
  storageClassName: managed-premium