---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: openmrs-rs
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: openmrs
  template:
    metadata:
      labels:
        app: openmrs
        version: "2.12"
    spec:
      containers:
        - name: openmrs-container
          image: openmrs:2.12
          livenessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          ports:
            - containerPort: 80
              protocol: TCP
              name: http